name: Backend CI

on:
  push:
    branches: ["master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'back-end'
    env:
      FRONT_END_URI: ${{ secrets.FRONT_END_URI }}
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING}}
      JWT_SECRET:  ${{ secrets.JWT_SECRET} 

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: echo "this is the build and test express.js job"
    - run: |
        npm install # install all dependencies listed in package.json
        npm run test # run all unit tests
